[build]
  command = "npm run build"
  publish = "dist/client"  # Updated to match Vite's output directory

[build.environment]
  NODE_VERSION = "18.x"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
