version: '3.8'

services:
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./client/package.json:/app/package.json
      - ./client/package-lock.json:/app/package-lock.json
      - ./client/src:/app/src
      - ./client/dist:/app/dist
    ports:
      - "3000:3000/tcp"
    expose:
      - "3000"
    networks:
      app-network:
        aliases:
          - frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: >
      sh -c "
      if [ ! -d node_modules ]; then npm install; fi
      npm run build
      npx serve -s dist -l 3000
      "

  api-server:
    image: node:18
    working_dir: /app
    volumes:
      - ./servers/package.json:/app/package.json
      - ./servers/package-lock.json:/app/package-lock.json
      - ./servers/src:/app/src
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: npm start

networks:
  app-network:
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1
